# Generated by Django 3.2 on 2021-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210427_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
